### ISSUE TITLE
Bug: set temperature has value 6553.5 on fan only

### ISSUE THREAD

**Issue by danielkaldheim** [danielkaldheim/ha_airstage#4]
[Weird bug for you, if you set the mode to Fan Only, the set temperature goes to 6553.5C](https://community.home-assistant.io/t/fujitsu-air-conditioning-integration-airstage-dongle/589679/131)

**Comment by gorstj** [comment]
I wonder if the integration should just not update the set temperature if the value= 6553.5? (i.e. leave it as the previous value)

Alternatively, it could be set as unavailable but that will be less useful for running automations off the currently set temperature.

**Comment by changeableface** [comment]
+1 this bug is making it tricky to setup some automations. 

Appreciate anything you can do to resolve.

**Comment by danielkaldheim** [comment]
Sorry for being AWOL. I will try to fix the bug tomorrow!

**Comment by danielkaldheim** [comment]
Fixed in 0a3da779ee324a395411157117aca85132a8f633

**Comment by changeableface** [comment]
Sorry to say I think this bug still exists. 

If my unit is set to 22, and then I turn on fan mode when exiting fan mode, it sets the temp to 6553.5 again.

It looks like this chap had the same issue and fixed it, if that's useful. 
https://github.com/bigmoby/fglair_for_homeassistant/issues/45

**Comment by bigmoby** [comment]
Hi @danielkaldheim if it could help you or give you some hints, I've tried to solve as follows:

```
    async def async_set_display_temperature_degree(self) -> float | None: 
         data = None 
         if self._adjust_temperature is not None: 
             adjust_temperature_value = self._adjust_temperature["value"] 
             if adjust_temperature_value == 65535: 
                 datapoints = await self._async_get_device_property_history( 
                     self._adjust_temperature["key"] 
                 ) 
                 # Get the latest setting other than invalid value 
                 for datapoint in reversed(datapoints): 
                     if datapoint["datapoint"]["value"] != 65535: 
                         adjust_temperature_value = int(datapoint["datapoint"]["value"]) 
                         break 
             data = round((adjust_temperature_value / 10), 1) 
         return data
```

In other words, I seek in history the last valid value.

**Comment by danielkaldheim** [comment]
Thank guys for reporting issues!

I did some changes in https://github.com/danielkaldheim/ha_airstage/releases/tag/v1.1.6 and hopefully this resolve the issue. Thanks @bigmoby!


I'll keep the issue open a few days just incase.

**Comment by changeableface** [comment]
Thanks for the update, sorry to say... I have come across an interest bug which I assume is connected...

If the unit is set to fan mode and then I attempt to turn it off, I get the following error pop up. 

_Failed to call service climate/set_hvac_mode. int() argument must be a string, a bytes-like object or a real number, not 'NoneType'_

If I set it to heat or cold I am then able to turn it off. 

This is running v.1.1.6

**Comment by danielkaldheim** [comment]
@changeableface thanks for reporting! I think I know why this is failing. I'll investigate.

**Comment by danielkaldheim** [comment]
Hopefully fixed in

**Comment by changeableface** [comment]
Yeah, that appears to have done the trick. 

Nice one bruva! 😎
